### ISSUE TITLE
Incorrect Features

### ISSUE THREAD

**Issue by 333fred** [exceptionnotfound/CSharp10Features#1]
Hi, this repository lists parameter null checking and the `field` keyword as features coming to C# 10. Neither of these are coming to C# 10.

**Comment by exceptionnotfound** [comment]
You are correct! The examples (and the corresponding blog posts) have been updated to reflect that these features are not included in C# 10. Here's hoping they get included at a later date.

**Comment by 333fred** [comment]
We hope to have them in 11, but no guarantees.
